project:
  title: "Interactive Data Visualisation Using the Teal Framework"
  output-dir: docs
  type: website
  render:
    - "*.qmd"
    - "README.md"

website:
  title: "Interactive Data Visualisation Using the Teal Framework"
  navbar:
    left:
      - href: index.qmd
        text: Home

